### ISSUE TITLE
Intermittent failures in CI: Unhandled exception

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-config#10]
Different tests fail from time to time on CI

```
SEVERE: Unhandled exception
java.util.concurrent.RejectedExecutionException: Task io.vertx.core.impl.TaskQueue$$Lambda$11/1613255205@3cd8b5c0 rejected from java.util.concurrent.ThreadPoolExecutor@321f5c2b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at io.vertx.core.impl.TaskQueue.execute(TaskQueue.java:78)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:291)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:235)
	at io.vertx.core.file.impl.FileSystemImpl$BlockingAction.run(FileSystemImpl.java:809)
	at io.vertx.core.file.impl.FileSystemImpl.readFile(FileSystemImpl.java:280)
	at io.vertx.config.spi.utils.FileSet.lambda$buildConfiguration$3(FileSet.java:85)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.vertx.config.spi.utils.FileSet.buildConfiguration(FileSet.java:81)
	at io.vertx.config.impl.spi.DirectoryConfigStore.lambda$get$4(DirectoryConfigStore.java:69)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:287)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

https://vertx.ci.cloudbees.com/job/vert.x3-config/407
https://vertx.ci.cloudbees.com/job/vert.x3-config/405
https://vertx.ci.cloudbees.com/job/vert.x3-config/390

**Comment by cescoffier** [comment]
It's not related to vert.x config, but it's an issue in Vert.x Core when a file access is done after (during ?) vert.x close.

**Comment by cescoffier** [comment]
I will wrap the code with a try / catch and fail the future.
