### ISSUE TITLE
Sometimes VaultConfigStoreTestBase#testWithRevokedRootToken fail

### ISSUE THREAD

**Issue by gaol** [vert-x3/vertx-config#108]
### Version
vertx-config:4.0.0-SNAPSHOT

### Steps to reproduce

In `vertx-config` root folder, run:
> mvn clean install

Sometimes the `VaultConfigStoreTestBase#testWithRevokedRootToken` will fail with the following exceptions:

<pre>
Jan 22, 2020 9:57:00 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.AssertionError: Expected true
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:362)
	at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:202)
	at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:208)
	at io.vertx.config.vault.VaultConfigStoreTestBase.lambda$null$19(VaultConfigStoreTestBase.java:403)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$getConfig$2(ConfigRetrieverImpl.java:182)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$compute$9(ConfigRetrieverImpl.java:285)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:127)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:175)
	at io.vertx.core.Promise.fail(Promise.java:90)
	at io.vertx.core.Promise.handle(Promise.java:54)
	at io.vertx.core.impl.CompositeFutureImpl.complete(CompositeFutureImpl.java:214)
	at io.vertx.core.impl.CompositeFutureImpl.fail(CompositeFutureImpl.java:207)
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$0(CompositeFutureImpl.java:46)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:127)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:175)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$null$6(ConfigRetrieverImpl.java:275)
	at io.vertx.config.impl.ConfigurationProvider.lambda$get$1(ConfigurationProvider.java:68)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:127)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:175)
	at io.vertx.core.Promise.fail(Promise.java:90)
	at io.vertx.core.Promise.handle(Promise.java:54)
	at io.vertx.core.Promise.handle(Promise.java:30)
	at io.vertx.core.impl.FailedFuture.onComplete(FailedFuture.java:55)
	at io.vertx.core.Future.setHandler(Future.java:111)
	at io.vertx.core.Future.lambda$compose$2(Future.java:272)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:127)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:175)
	at io.vertx.core.Promise.fail(Promise.java:90)
	at io.vertx.core.Promise.handle(Promise.java:54)
	at io.vertx.core.Promise.handle(Promise.java:30)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:127)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:175)
	at io.vertx.core.Promise.fail(Promise.java:90)
	at io.vertx.config.vault.VaultConfigStore.lambda$retrieve$3(VaultConfigStore.java:119)
	at io.vertx.config.vault.client.SlimVaultClient.lambda$read$0(SlimVaultClient.java:90)
	at io.vertx.ext.web.client.impl.HttpContext.handleFailure(HttpContext.java:304)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:298)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:270)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:267)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:277)
	at io.vertx.ext.web.client.impl.HttpContext.fail(HttpContext.java:257)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$handleSendRequest$8(HttpContext.java:416)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:127)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:175)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$handleSendRequest$9(HttpContext.java:424)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
	at io.vertx.core.impl.AbstractContext.lambda$dispatch$0(AbstractContext.java:84)
	at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:58)
	at io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:94)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:84)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:175)
	at io.vertx.core.http.impl.HttpClientRequestBase.fail(HttpClientRequestBase.java:111)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:106)
	at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:86)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleException(Http1xClientConnection.java:465)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleClosed(Http1xClientConnection.java:470)
	at io.vertx.core.http.impl.Http1xClientConnection.lambda$handleClosed$8(Http1xClientConnection.java:843)
	at io.vertx.core.impl.EventLoopContext.lambda$schedule$2(EventLoopContext.java:60)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Jan 22, 2020 9:57:00 PM io.vertx.core.http.impl.HttpClientRequestImpl
SEVERE: io.vertx.core.VertxException: Connection was closed

</pre>

**Comment by vietj** [comment]
it might be a race in the test or a bug

**Comment by gaol** [comment]
Sometimes I see the following exceptions while it failed:

    Caused by: io.vertx.core.VertxException: Connection was closed

Repeating the single test: `-Dtest=VaultConfigStoreWithTokenCreationTest#testWithRevokedRootToken` can reproduce it as well.

So it looks like an issue in this test, I will investigate it.
