### ISSUE TITLE
CI build error

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-config#59]
on Java 8:

```
testDeploymentOfVerticles(io.vertx.config.verticle.VerticleDeploymentTest)  Time elapsed: 0.042 sec  <<< FAILURE!
java.lang.AssertionError: Expected true
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:467)
	at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:307)
	at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:313)
	at io.vertx.config.verticle.VerticleDeploymentTest.lambda$null$1(VerticleDeploymentTest.java:54)
Oct 02, 2018 8:55:33 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.AssertionError: Expected true
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:467)
	at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:307)
	at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:313)
	at io.vertx.config.verticle.VerticleDeploymentTest.lambda$null$1(VerticleDeploymentTest.java:54)
	at io.vertx.core.eventbus.impl.HandlerRegistration.sendAsyncResultFailure(HandlerRegistration.java:127)
	at io.vertx.core.eventbus.impl.EventBusImpl.deliverMessageLocally(EventBusImpl.java:367)
	at io.vertx.core.eventbus.impl.EventBusImpl.sendOrPub(EventBusImpl.java:332)
	at io.vertx.core.eventbus.impl.EventBusImpl$OutboundDeliveryContext.next(EventBusImpl.java:483)
	at io.vertx.core.eventbus.impl.EventBusImpl.sendOrPubInternal(EventBusImpl.java:440)
	at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:111)
	at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:101)
	at io.vertx.config.verticle.VerticleDeploymentTest.lambda$testDeploymentOfVerticles$2(VerticleDeploymentTest.java:53)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$getConfig$2(ConfigRetrieverImpl.java:180)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$compute$9(ConfigRetrieverImpl.java:294)
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$null$6(ConfigRetrieverImpl.java:264)
	at io.vertx.config.impl.ConfigurationProvider.lambda$null$0(ConfigurationProvider.java:83)
	at io.vertx.config.impl.spi.JsonProcessor.process(JsonProcessor.java:42)
	at io.vertx.config.impl.ConfigurationProvider.lambda$get$1(ConfigurationProvider.java:71)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cescoffier** [comment]
How do you reproduce it?
