### ISSUE TITLE
RefNotFoundException is thrown when start with another branch

### ISSUE THREAD

**Issue by hoangnam2261** [vert-x3/vertx-config#95]
After I got configuration from a branch, I change parameter "path" to get configuration on another branch WITHOUT deleting old local repo, a RefNotFoundException will be thrown with this call stack: 
Caused by: org.eclipse.jgit.api.errors.RefNotFoundException: Ref dev can not be resolved
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:251)
	at io.vertx.config.git.GitConfigStore.initializeGit(GitConfigStore.java:145)
	at io.vertx.config.git.GitConfigStore.<init>(GitConfigStore.java:122)

Version: 3.7.0

**Comment by SINGS079** [comment]
Any use case for picking configs from different branches?
